default:
  pull_request_rules:
    - name: Automatic merge on CI success
      conditions:
        - status-success=continuous-integration/appveyor/pr
        - base=master
      actions:
        merge:
          method: merge
