language: python
python:
- 3.6.7
- 3.7
script:
- coverage run -m pytest
install:
- pip install -r dev.txt
after_success:
- codecov
- python-codacy-coverage -r coverage.xml
branches:
  only:
  - master