language: python
python:
  - "2.7"
script:
  - python -m unittest test
  - coverage run --source=tvsort_sl tvsort_sl/tvsort_sl.py test
after_success:
  coveralls
notifications:
  email:
    on_success: never
os:
  - "win"