language: python
python:
  - "2.7"
  - “3.6”
  - “3.5”
script:
  - python -m unittest test
  - coverage run --source=tvsort_sl tvsort_sl/tvsort_sl.py test
after_success:
  coveralls
notifications:
  email:
    on_success: never
install:
  - pip install _winreg
  - pip install pypiwin32
os:
  - "win"
  - "windows"