language: python
python:
- 3.6.7
- 3.7
script:
- mkdir logs
- cp ./tvsort_sl/settings/templates/local.yml ./tvsort_sl/settings/local.yml
- cp ./tvsort_sl/settings/templates/test.yml ./tvsort_sl/settings/test.yml
- coverage run -m pytest
install:
- pip install -r dev.txt
after_success:
- codecov
- python-codacy-coverage -r coverage.xml
branches:
  only:
  - master