name: Run Reviewdog with Black and Flake8

on: [pull_request]

jobs:
  lint:
    name: Run Black and Flake8
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.7"

      - name: Install Reviewdog
        uses: reviewdog/action-setup@v1

      - name: Reviewdog version
        run: reviewdog -version

      - name: Install dependencies
#        TODO: add versions
        run: |
          pip install black flake8==3.7.6

      - name: Run Black
        run: black --check .
        continue-on-error: true

      - name: Run Flake8
        run: flake8 .
        continue-on-error: true

      - name: Reviewdog Reporting
        uses: reviewdog/action-flake8@v3
        with:
          reporter: github-pr-review
          level: error
          fail_on_error: true
          filter_mode: added
