name: Run Reviewdog with Black and Flake8

on: [pull_request]

jobs:
  lint:
    name: Run Black and Flake8
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

#      - uses: reviewdog/action-black@v3
#        with:
#          github_token: ${{ secrets.github_token }}
#          # Change reviewdog reporter if you need [github-pr-check, github-check].
#          reporter: github-pr-check
#          # Change reporter level if you need.
#          # GitHub Status Check won't become failure with a warning.
#          level: error
#
      - uses: dciborow/action-pylint@0.1.0
        with:
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: github-pr-review
          # Change reporter level if you need.
          # GitHub Status Check won't become failure with warning.
          level: error

#      - name: wemake-python-styleguide
#        uses: wemake-services/wemake-python-styleguide@0.19.2
#        with:
#          reporter: 'github-pr-review'
#        env:
#          GITHUB_TOKEN: ${{ secrets.github_token }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wemake-python-styleguide
      - name: WemakeLint
        run: |
          flake8
