name: Run Reviewdog with Black and Flake8

on: [pull_request]

jobs:
  lint:
    name: Run Black and Flake8
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.7"

      - name: Install Reviewdog
        uses: reviewdog/action-setup@v1

      - name: Reviewdog version
        run: reviewdog -version

      - name: Install dependencies
#        TODO: add versions
        run: |
          pip install black flake8==3.7.6

      - name: wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide
#      - name: Run reviewdog
#        env:
#          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          reviewdog -reporter=github-check -runners=flake8